force-app/main/default/objects/ContentVersion/fields/Expiry_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_From_Date__c</fullName>
    <label>​​Expiry​ ​From​ ​Date​​</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Expiry_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_To_Date__c</fullName>
    <label>Expiry​ ​To​ ​Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <description>This is a custom object for storing information about a voucher to be printed</description>
    <label>Credit​ ​Memo</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Credit​ ​Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit​ ​Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/Credit_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Expiry_Date__c</fullName>
    <label>Credit Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo_Config__c/Credit_Memo_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object stores a settings for the Credit Memo object and pdf-voucher</description>
    <label>Credit Memo Config</label>
</CustomObject>

force-app/main/default/objects/Credit_Memo_Config__c/fields/Library_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Library_Unique_Name__c</fullName>
    <description>This a content library unique name for storing Default/Global images for the pdf rendering</description>
    <label>Library Unique Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo_Config__c/fields/Note_Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Note_Default_Value__c</fullName>
    <defaultValue>&#39;. Valid for these countries&#39; &amp;
&#39;. Valid for&#39; &amp; 
&#39;. Valid for&#39;</defaultValue>
    <description>The default value for Note field on Credit Memo object</description>
    <label>Note Default Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DefaultFilePreviewCtrlTest.cls
@isTest
private class DefaultFilePreviewCtrlTest {

    @testSetup
    private static void setupTestData() {
        ContentWorkspace library = new ContentWorkspace(
            Name = 'Global Image Test',
            DeveloperName = 'Global_Image_Test'
        );
        insert library;
    }

    private static void setupCustomSettign() {
        Credit_Memo_Config__c settings = new Credit_Memo_Config__c(
            Library_Unique_Name__c	= 'Global_Image_Test',
            Note_Default_Value__c = '. Valid term 1\n.Valid term 2\n.Valid term 3'
        );

        insert settings;
    }

    @isTest
    private static void getDefaultImageId() {
        ContentWorkspace library = [SELECT Id FROM ContentWorkspace WHERE DeveloperName = 'Global_Image_Test' LIMIT 1];
        ContentVersion cv = new ContentVersion(
            Title = 'Image 1',
            PathOnClient = 'Image1.jpg',
            VersionData = Blob.valueof('TestImageData'),
            IsMajorVersion = true,
            FirstPublishLocationId = library.Id,
            Expiry_From_Date__c = Date.newinstance(2020, 1, 17),
            Expiry_To_Date__c = Date.newinstance(2020, 1, 20)
        );
        insert cv;

        Credit_Memo__c creditMemo = new Credit_Memo__c(
            Credit_Expiry_Date__c = Date.newinstance(2020, 1, 18)
        );
        insert creditMemo;

        DefaultFilePreviewCtrlTest.setupCustomSettign();
        Test.startTest();
        String contentDocumentId = DefaultFilePreviewCtrl.getDefaultImageId(creditMemo.Id);
        Test.stopTest();
        Id contentDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id LIMIT 1].ContentDocumentId;

        System.assertEquals(contentDocId, contentDocumentId, 'The content document id was not found correctly');
    }

    @isTest
    private static void getDefaultImageIdError() {
        ContentWorkspace library = [SELECT Id FROM ContentWorkspace WHERE DeveloperName = 'Global_Image_Test' LIMIT 1];
        ContentVersion cv = new ContentVersion(
            Title = 'Image 1',
            PathOnClient = 'Image1.jpg',
            VersionData = Blob.valueof('TestImageData'),
            IsMajorVersion = true,
            FirstPublishLocationId = library.Id,
            Expiry_From_Date__c = Date.newinstance(2020, 1, 17),
            Expiry_To_Date__c = Date.newinstance(2020, 1, 20)
        );
        insert cv;

        Credit_Memo__c creditMemo = new Credit_Memo__c(
            Credit_Expiry_Date__c = Date.newinstance(2020, 1, 18)
        );
        insert creditMemo;

        Test.startTest();
        try {
            String contentDocumentId = DefaultFilePreviewCtrl.getDefaultImageId(creditMemo.Id);
        }
        catch(AuraException e) {
            System.assert(e.getMessage().contains('Please check settings.'), 'The expected error was not thrown');
        }
        Test.stopTest();
    }
}