force-app/main/default/objects/ContentVersion/fields/Expiry_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_From_Date__c</fullName>
    <label>​​Expiry​ ​From​ ​Date​​</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Expiry_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_To_Date__c</fullName>
    <label>Expiry​ ​To​ ​Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Unique_Title__c.field-meta.xml
<CustomField>
    <fullName>Unique_Title__c</fullName>
    <displayFormat>Image-{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Unique Title</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <description>This is a custom object for storing information about a voucher to be printed</description>
    <label>Credit​ ​Memo</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Credit​ ​Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit​ ​Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/Background_Image__c.field-meta.xml
<CustomField>
    <fullName>Background_Image__c</fullName>
    <description>This a link to the file which can be used to override the default background image of pdf.</description>
    <inlineHelpText>To link a necessary background image to this record put here the file&#39;s Unit Title value.</inlineHelpText>
    <label>Background Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Credit_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Expiry_Date__c</fullName>
    <label>Credit Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <defaultValue>$Setup.Credit_Memo_Config__c.Note_Default_Value__c</defaultValue>
    <description>This a field for saving Ts and Cs for the voucher</description>
    <inlineHelpText>Please use a dot sign at the beginning of the line to mark the line as a separate list item.</inlineHelpText>
    <label>Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Credit_Memo_Config__c/Credit_Memo_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object stores a settings for the Credit Memo object and pdf-voucher</description>
    <label>Credit Memo Config</label>
</CustomObject>

force-app/main/default/objects/Credit_Memo_Config__c/fields/Library_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Library_Unique_Name__c</fullName>
    <description>This a content library unique name for storing Default/Global images for the pdf rendering</description>
    <label>Library Unique Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo_Config__c/fields/Note_Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Note_Default_Value__c</fullName>
    <defaultValue>&#39;. Valid for these countries&#39; &amp;
&#39;. Valid for&#39; &amp; 
&#39;. Valid for&#39;</defaultValue>
    <description>The default value for Note field on Credit Memo object</description>
    <label>Note Default Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PrintVoucherCtrlTest.cls
@isTest
private class PrintVoucherCtrlTest {

    @testSetup
    private static void setupTestData() {
        ContentWorkspace library = new ContentWorkspace(
            Name = 'Global Image Test',
            DeveloperName = 'Global_Image_Test'
        );
        insert library;
    }

    private static void setupCustomSettign() {
        Credit_Memo_Config__c settings = new Credit_Memo_Config__c(
            Library_Unique_Name__c	= 'Global_Image_Test',
            Note_Default_Value__c = '. Valid term 1\n.Valid term 2\n.Valid term 3'
        );

        insert settings;
    }

    @isTest
    private static void initPageWithDefaultImageTest() {
        ContentWorkspace library = [SELECT Id FROM ContentWorkspace WHERE DeveloperName = 'Global_Image_Test' LIMIT 1];
        ContentVersion cv = new ContentVersion(
            Title = 'Image 1',
            PathOnClient = 'Image1.jpg',
            VersionData = Blob.valueof('TestImageData'),
            IsMajorVersion = true,
            FirstPublishLocationId = library.Id,
            Expiry_From_Date__c = Date.newinstance(2020, 1, 17),
            Expiry_To_Date__c = Date.newinstance(2020, 1, 20)
        );
        insert cv;

        Credit_Memo__c creditMemo = new Credit_Memo__c(
            Credit_Expiry_Date__c = Date.newinstance(2020, 1, 18),
            Note__c = '. Valid term 1\n.Valid term 2\n.Valid term 3'
        );
        insert creditMemo;

        PrintVoucherCtrlTest.setupCustomSettign();
        Test.startTest();
        ApexPages.StandardController standardCtrl = new ApexPages.StandardController(creditMemo);
        PrintVoucherCtrl extentionCtrl = new PrintVoucherCtrl(standardCtrl);
        Test.stopTest();

        System.assertEquals(PrintVoucherCtrl.CONTENT_VERSION_ACCESS_URL + cv.Id, extentionCtrl.imageUrl, 'The image url was not set as expected');
        System.assertEquals(3, extentionCtrl.notes.size(), 'Note field was not parsed correctly');
    }

    @isTest
    private static void initPageWithOverrideImageTest() {
        ContentWorkspace library = [SELECT Id FROM ContentWorkspace WHERE DeveloperName = 'Global_Image_Test' LIMIT 1];
        List<ContentVersion> contentVersions = new List<ContentVersion>();
        ContentVersion cv1 = new ContentVersion(
            Title = 'Image 1',
            PathOnClient = 'Image1.jpg',
            VersionData = Blob.valueof('TestImageData1'),
            IsMajorVersion = true,
            FirstPublishLocationId = library.Id,
            Expiry_From_Date__c = Date.newinstance(2020, 1, 17),
            Expiry_To_Date__c = Date.newinstance(2020, 1, 20)
        );
        ContentVersion cv2 = new ContentVersion(
            Title = 'Image 2',
            PathOnClient = 'Image2.jpg',
            VersionData = Blob.valueof('TestImageData2'),
            IsMajorVersion = true,
            FirstPublishLocationId = library.Id,
            Expiry_From_Date__c = Date.newinstance(2020, 1, 17),
            Expiry_To_Date__c = Date.newinstance(2020, 1, 20)
        );
        contentVersions.add(cv1);
        contentVersions.add(cv2);
        insert contentVersions;

        ContentVersion selectedCV = [SELECT Unique_Title__c FROM ContentVersion WHERE Id =: cv2.Id LIMIT 1];
        Credit_Memo__c creditMemo = new Credit_Memo__c(
            Credit_Expiry_Date__c = Date.newinstance(2020, 1, 18),
            Background_Image__c = selectedCV.Unique_Title__c
        );
        insert creditMemo;

        PrintVoucherCtrlTest.setupCustomSettign();
        Test.startTest();
        ApexPages.StandardController standardCtrl = new ApexPages.StandardController(creditMemo);
        PrintVoucherCtrl extentionCtrl = new PrintVoucherCtrl(standardCtrl);
        Test.stopTest();

        System.assertEquals(PrintVoucherCtrl.CONTENT_VERSION_ACCESS_URL + cv2.Id, extentionCtrl.imageUrl, 'The image url was not set as expected');
    }

    @isTest
    private static void initPageWithConfigErrorTest() {
        ContentWorkspace library = [SELECT Id FROM ContentWorkspace WHERE DeveloperName = 'Global_Image_Test' LIMIT 1];
        ContentVersion cv = new ContentVersion(
            Title = 'Image 1',
            PathOnClient = 'Image1.jpg',
            VersionData = Blob.valueof('TestImageData'),
            IsMajorVersion = true,
            FirstPublishLocationId = library.Id,
            Expiry_From_Date__c = Date.newinstance(2020, 1, 17),
            Expiry_To_Date__c = Date.newinstance(2020, 1, 20)
        );
        insert cv;

        Credit_Memo__c creditMemo = new Credit_Memo__c(
            Credit_Expiry_Date__c = Date.newinstance(2020, 1, 18)
        );
        insert creditMemo;

        Test.startTest();
        ApexPages.StandardController standardCtrl = new ApexPages.StandardController(creditMemo);
        try {
            PrintVoucherCtrl extentionCtrl = new PrintVoucherCtrl(standardCtrl);
        }
        catch(CannotFindContentException e) {
            System.assert(e.getMessage().contains('Please check settings.'), 'The expected error was not thrown');
        }
        Test.stopTest();
    }

    private static void initPageWithFileNameErrorTest() {
        Credit_Memo__c creditMemo = new Credit_Memo__c(
            Credit_Expiry_Date__c = Date.newinstance(2020, 1, 18),
            Background_Image__c = 'Wrong_Unique_Name'
        );
        insert creditMemo;

        PrintVoucherCtrlTest.setupCustomSettign();
        Test.startTest();
        ApexPages.StandardController standardCtrl = new ApexPages.StandardController(creditMemo);
        try {
            PrintVoucherCtrl extentionCtrl = new PrintVoucherCtrl(standardCtrl);
        }
        catch(CannotFindContentException e) {
            System.assert(e.getMessage().contains('not able to find an image based on specified Unique Title'), 'The expected error was not thrown');
        }
        Test.stopTest();
    }

    @isTest
    private static void initPageWithExpireDateErrorTest() {
        ContentWorkspace library = [SELECT Id FROM ContentWorkspace WHERE DeveloperName = 'Global_Image_Test' LIMIT 1];
        ContentVersion cv = new ContentVersion(
            Title = 'Image 1',
            PathOnClient = 'Image1.jpg',
            VersionData = Blob.valueof('TestImageData'),
            IsMajorVersion = true,
            FirstPublishLocationId = library.Id,
            Expiry_From_Date__c = Date.newinstance(2020, 1, 17),
            Expiry_To_Date__c = Date.newinstance(2020, 1, 20)
        );
        insert cv;

        Credit_Memo__c creditMemo = new Credit_Memo__c(
            Credit_Expiry_Date__c = Date.newinstance(2022, 1, 18)
        );
        insert creditMemo;

        PrintVoucherCtrlTest.setupCustomSettign();
        Test.startTest();
        ApexPages.StandardController standardCtrl = new ApexPages.StandardController(creditMemo);
        try {
            PrintVoucherCtrl extentionCtrl = new PrintVoucherCtrl(standardCtrl);
        }
        catch(CannotFindContentException e) {
            System.assert(e.getMessage().contains('not able to find an image based on specified Expire Date'), 'The expected error was not thrown');
        }
        Test.stopTest();
    }
}