force-app/main/default/objects/ContentVersion/fields/Expiry_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_From_Date__c</fullName>
    <label>​​Expiry​ ​From​ ​Date​​</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Expiry_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_To_Date__c</fullName>
    <label>Expiry​ ​To​ ​Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Unique_Title__c.field-meta.xml
<CustomField>
    <fullName>Unique_Title__c</fullName>
    <displayFormat>Image-{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Unique Title</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/ContentDocumentSelector.cls
public with sharing class ContentDocumentSelector {

    public static Id getContentDocumentIdByExpireDate(Date expireDate, String libraryUniqueName) {
        
        return ContentDocumentSelector.getContentVersionByExpireDate(expireDate, libraryUniqueName).ContentDocumentId;
    }

    public static Id getContentVersionIdByExpireDate(Date expireDate, String libraryUniqueName) {
        
        return ContentDocumentSelector.getContentVersionByExpireDate(expireDate, libraryUniqueName).Id;
    }

    public static Id getContentVersionIdByUniqueTitle(String uniqueTitle) {
        List <ContentVersion> contentDocuments = [
            SELECT Id 
            FROM ContentVersion 
            WHERE Unique_Title__c = :uniqueTitle
            ORDER BY CreatedDate DESC 
            LIMIT 1
        ];

        if (contentDocuments.isEmpty()) {
            throw new CannotFindContentException('We\'re not able to find an image based on specified Unique Title. Please check configuration');
        }

        return contentDocuments.get(0).Id;
    }

    private static ContentVersion getContentVersionByExpireDate(Date expireDate, String libraryUniqueName) {
        List<ContentWorkspace> contentLibraries = [
            SELECT Id 
            FROM ContentWorkspace 
            WHERE DeveloperName = :libraryUniqueName
            LIMIT 1
        ];
        if (contentLibraries.isEmpty()) {
            throw new CannotFindContentException('We\'re not able to find the library by specified unique name. Please check Credit Memo Config settings');
        }

        List <ContentVersion> contentDocuments = [
            SELECT Id, ContentDocumentId
            FROM ContentVersion 
            WHERE ContentDocument.ParentId = :contentLibraries.get(0).Id
                AND isLatest = true
                AND Expiry_From_Date__c <= :expireDate
                AND Expiry_To_Date__c >= :expireDate
            ORDER BY CreatedDate DESC 
            LIMIT 1
        ];

        if (contentDocuments.isEmpty()) {
            throw new CannotFindContentException('We\'re not able to find an image based on specified Expire Date and Content Library name. Please check configuration');
        }

        return contentDocuments.get(0);
    }
}