force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <description>This is a custom object for storing information about a voucher to be printed</description>
    <label>Credit​ ​Memo</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Credit​ ​Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit​ ​Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/Background_Image__c.field-meta.xml
<CustomField>
    <fullName>Background_Image__c</fullName>
    <description>This a link to the file which can be used to override the default background image of pdf.</description>
    <inlineHelpText>To link a necessary background image to this record put here the file&#39;s Unit Title value.</inlineHelpText>
    <label>Background Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Credit_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Expiry_Date__c</fullName>
    <label>Credit Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo_Config__c/Credit_Memo_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object stores a settings for the Credit Memo object and pdf-voucher</description>
    <label>Credit Memo Config</label>
</CustomObject>

force-app/main/default/objects/Credit_Memo_Config__c/fields/Library_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Library_Unique_Name__c</fullName>
    <description>This a content library unique name for storing Default/Global images for the pdf rendering</description>
    <label>Library Unique Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PrintVoucherCtrl.cls
public with sharing class PrintVoucherCtrl {

    private final Credit_Memo__c creditMemoRecord;
    public String imageUrl {get; set;}
    public String message {get; set;}


    public PrintVoucherCtrl(ApexPages.StandardController stdController) {
        stdController.addFields(new List<String>{'Credit_Expiry_Date__c', 'Background_Image__c'});
        this.creditMemoRecord = (Credit_Memo__c) stdController.getRecord();

        Credit_Memo_Config__c config = Credit_Memo_Config__c.getInstance();
        if (config == null || config.Library_Unique_Name__c == null) {
            this.message = 'The Credit Memo Config or Files Library Unique name doesn\'t set. Please check settings.';
            return;
        }

        // try {
            Id contentVersionId;

            if (this.creditMemoRecord.Background_Image__c != null) {
                contentVersionId = ContentDocumentSelector.getContentVersionIdByUniqueTitle(this.creditMemoRecord.Background_Image__c);
            }
            else {
                contentVersionId = ContentDocumentSelector.getContentVersionIdByExpireDate(
                                                        this.creditMemoRecord.Credit_Expiry_Date__c, config.Library_Unique_Name__c);
            }   

            this.imageUrl = '/sfc/servlet.shepherd/version/renditionDownload?rendition=THUMB720BY480&versionId=' + contentVersionId;
        // }
        // catch(CannotFindContentException e) {
        //     this.message = e.getMessage();
        // }
    }
}