force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <description>This is a custom object for storing information about a voucher to be printed</description>
    <label>Credit​ ​Memo</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Credit​ ​Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit​ ​Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/Credit_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Expiry_Date__c</fullName>
    <label>Credit Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo_Config__c/Credit_Memo_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object stores a settings for the Credit Memo object and pdf-voucher</description>
    <label>Credit Memo Config</label>
</CustomObject>

force-app/main/default/objects/Credit_Memo_Config__c/fields/Library_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Library_Unique_Name__c</fullName>
    <description>This a content library unique name for storing Default/Global images for the pdf rendering</description>
    <label>Library Unique Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DefaultFilePreviewCtrl.cls
public with sharing class DefaultFilePreviewCtrl {

    @AuraEnabled
    public static String getDefaultImageId(String creditMemoId) {

        Credit_Memo_Config__c config = Credit_Memo_Config__c.getInstance();
        if (config == null || config.Library_Unique_Name__c == null) {
            throw new AuraException('The Credit Memo Config or Files Library Unique name doesn\'t set. Please check settings.');
        }
        List<Credit_Memo__c> creditMemos = [
            SELECT Credit_Expiry_Date__c 
            FROM Credit_Memo__c 
            WHERE Id = :creditMemoId
            LIMIT 1
        ];

        return ContentDocumentSelector.getContentDocumentIdByExpireDate(
                                                        creditMemos.get(0).Credit_Expiry_Date__c, config.Library_Unique_Name__c);
    }
}